services:
  server:
    build: ./server
    container_name: blackjack-server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL_LIST: ${SERVER_URL_LIST}
    container_name: blackjack-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL_LIST=${SERVER_URL_LIST}
